export * from './tipo-vehiculo.repository';
export * from './administrador.repository';
export * from './asesor.repository';
export * from './cliente.repository';
export * from './codeudor.repository';
export * from './roles.repository';
export * from './solicitud.repository';
export * from './vehiculo.repository';
export * from './sede.repository';
